include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    require_trailing_commas: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    use_key_in_widget_constructors: false

analyzer:
  strong-mode:
    implicit-dynamic: true
  exclude:
    - "lib/generated/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
